dist: xenial
language: python
python:
  - "3.7"
  - "nightly"
# command to install dependencies
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda env create -f environment_cpu.yml
  - conda activate pytorch_rcnn_cpu
# command to run tests
script:
  - python -m unittest discover "./test" -p "test_*.py"
  