name: pytorch_rcnn_cpu
channels:
  - pytorch
  - defaults
dependencies:
  - python>=3.7
  - pytorch-cpu
  - torchvision-cpu
  - pillow
  - flake8
  - pip:
    - coverage
    - opencv-python
    - tqdm
    - ujson
