name: pytorch_rcnn_gpu
channels:
  - pytorch
  - defaults
dependencies:
  - pytorch
  - torchvision
  - cudatoolkit=10.0
  - pillow
  - flake8
  - pip
  - jupyter
  - matplotlib
  - pip:
    - coverage
    - opencv-python
    - tqdm
    - ujson

